# Generated by Django 3.0.4 on 2020-06-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_auto_20200624_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
