# Generated by Django 3.0.4 on 2020-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0007_questions_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='img',
        ),
        migrations.AddField(
            model_name='answers',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
