# Generated by Django 3.0.4 on 2020-06-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0008_auto_20200624_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
